apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: database
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==  # Base64 encoded "mongoadmin"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dk          # Base64 encoded "passwd"

---

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: admin
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==  # Base64 encoded "mongoadmin"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dk          # Base64 encoded "passwd"

---

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: user
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==  # Base64 encoded "mongoadmin"
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dk          # Base64 encoded "passwd"
