apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: user  # Correct namespace for your services
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Strip the /admin path for backend services
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: admin-ui  # The name of the admin-ui service
            port:
              number: 3001
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user-ui  # The name of the user-ui service
            port:
              number: 3002




