apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: database
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:  # <-- The missing spec block!
      nodeSelector:
        role: database  # Ensure it runs on the correct node
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          resources:
            requests:
              memory: "1000Mi"
              cpu: "500m"
            limits:
              memory: "2000Mi"
              cpu: "1300m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: database
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None  # Headless service for direct pod access

